pav_s00:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Velocity Controllers ----速度控制器---------------------
  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_rear_wheel_link_joint
    pid: {p: 0.1, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_rear_wheel_link_joint
    pid: {p: 0.1, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_front_wheel_link_joint
    pid: {p: 0.1, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_front_wheel_link_joint
    pid: {p: 0.1, i: 0.0, d: 0.0, i_clamp: 0.0}

  # Position Controllers ---位置控制器-----------------------
  left_steering_hinge_position_controller:
    joint: left_front_steer_hinge_link_joint
    type: effort_controllers/JointPositionController
    pid: {p: 10, i: 0.0, d: 0}
  right_steering_hinge_position_controller:
    joint: right_front_steer_hinge_link_joint
    type: effort_controllers/JointPositionController
    pid: {p: 10, i: 0.0, d: 0}

